<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by Softradix</title>
</head>
<body>
Hello  {{ ucfirst($details['name']) }}<br><br>
Welcome to Softradix.<br>
Here are the credentials to access our system.<br>
Email: {{ $details['email'] }}<br>
Password:  {{ $details['password'] }}<br><br>
Click here to login<br>
<a href="{{ $details['link'] }}">{{ $details['link'] }}<a><br><br>
Thanks,<br>
Team Softradix<br>

</body>
</html>
